q01:
	mpicc -o questao01 questao01.c
	mpirun -np 8 questao01
q01_clean:
	rm questao01

q03:
	mpicc -o questao03 questao03.c
	mpirun -np 4 questao03 20

q05:
	mpicc -o questao05 questao05.c
	mpirun -np 4 questao05 1000000

clean:
	rm questao01 questao03 questao02
